mode: matcher
log_level: debug
matcher:
  http_listen_addr: :80
  indexer_addr: http://indexer/
  connstring: host=clair-db port=5432 user=clair dbname=clair sslmode=disable
  max_conn_pool: 100
  migrations: true
